management:
  endpoint:
    env:
      show-values: always
    health:
      access: read_only
      show-details: always
  endpoints:
    web:
      exposure:
        include: env,configprops,refresh
  health:
    db:
      enabled: false
    diskspace:
      enabled: true
spring:
  application:
    name: licensing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8071